# Generated by Django 5.1.4 on 2026-06-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_order_number_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_mode',
            field=models.CharField(choices=[('payg', 'Pay As You Go (platform 2%)'), ('own', 'Own payment methods')], default='payg', max_length=10),
        ),
    ]
