# Generated by Django 5.1.4 on 2026-06-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_onboarding_complete', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_provider', to='tenants.tenant')),
            ],
        ),
    ]
